# Generated by Django 4.2.5 on 2023-10-16 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_chatroom_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unread_by',
            field=models.ManyToManyField(related_name='unread_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
